### ISSUE TITLE
feat: Alternative labels for minor and major labels can be specified

### ISSUE THREAD

**Issue by k2tzumi** [Songmu/tagpr#139]
# Motive

I would like to avoid setting a separate label for tagpr when the release notes are set to be automatically generated as follows
https://docs.github.com/ja/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations

* .github/release.yml
  ```yml
  changelog:
    exclude:
      labels:
        - ignore-for-release
      authors:
        - octocat
    categories:
      - title: Breaking Changes 🛠
        labels:
          - Semver-Major
          - breaking-change
      - title: Exciting New Features 🎉
        labels:
          - Semver-Minor
          - enhancement
      - title: Other Changes
        labels:
          - "*"
  ```

For example, if it has a `breaking-change` label, we want to treat it as a major version up.

# Proposal

How about adding the following options to the `.tagpr` configuration file?

```
[tagpr]
	vPrefix = true
	releaseBranch = main
	versionFile = version.go,action.yml
        majorLabels = major,breaking-change
        minorLabels = minor,enhancement
```

Allows multiple labels to be specified for `majorLabels` and `minorLabels`, respectively.
