### ISSUE TITLE
[Question] about "What't changed" in pull-request body

### ISSUE THREAD

**Issue by hironemu** [Songmu/tagpr#167]
I am using `staging` branch for releaseBranch. In this case, the "What's changed" that should appear in the body of the PR is not output.  -  It worked fine when I was using the main branch. - 
<img width="923" alt="image" src="https://github.com/Songmu/tagpr/assets/1174500/aba9a75c-511d-4133-af94-13d40112410a">

my configuration is as follows:

.github/workflows/tagpr.yml
```yml
name: tagpr
on:
  push:
    branches: ["staging"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: tagpr
        uses: Songmu/tagpr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

.tagpr
```
[tagpr]
	vPrefix = true
	releaseBranch = staging
	versionFile = -
```

However, release notes created after the release PRs have been merged will show the correct changelog.
<img width="632" alt="image" src="https://github.com/Songmu/tagpr/assets/1174500/5d2a19cc-4d5f-4b57-8498-2720b1a8c9ec">
