### ISSUE TITLE
[Question] How to create PR to 'production' branch?

### ISSUE THREAD

**Issue by PaulSxxxs** [Songmu/tagpr#171]
Hello,
We're starting to play with tagpr and we absolutely love the changelist and contributors in each PR.
However, I'm struggling to make the PR's target our `production` branch and it always wants to merge to `master` instead.
Ideally we want to pick up all changes and merge them to `production` instead ... my understanding is that my config should work?

Where am i going wrong?
Thanks!

```
name: tagpr
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 19 * * *' # cron job every day at 5:00 AM Sydney time during standard time
    # - cron:  '0 18 * * *' #cron job every day at 5:00 AM Sydney time  during daylight saving time
  push:
    branches: ["production"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
